name: AutoClash

on: [push]

jobs:
  job1:
    runs-on: ubuntu-latest
    env:
      TZ: Asia/Shanghai
      
    timeout-minutes: 10
    steps:
    - uses: actions/checkout@v3
    - run: docker build -t levenwindy/clash:0.1 docker/.
    - run: docker images
    - run: docker ps -a
    -
      name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    -
      name: Push
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: levenwindy/clash:0.1
    





