name: AutoClash
on: [push]
jobs:
  job1:
    runs-on: ubuntu-latest
    env:
      VER: "0.2"
      DH: "${{ secrets.DOCKERHUB_USERNAME }}/autoclash"
      TZ: Asia/Shanghai
    timeout-minutes: 10
    steps:
    - uses: actions/checkout@v3
    - run: docker build -t $DH:$VER docker/.
    -
      name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - 
      name: Push
      run: docker push $DHV
    - run: docker run -itd --privileged --name=clash ${{ secrets.DOCKERHUB_USERNAME }}/autoclash:0.2 bash
    - run: docker ps
    - run: docker ps -a
    - run: docker logs clash
    - run: docker exec clash ps aux
    - run: docker exec clash echo 'Direct ip' ;curl -s cip.cc | sed '4,100d' ; echo ''; echo 'Proxy ip' ; curl icanhazip.com
    - run: docker exec clash ./start.sh
    - run: docker exec clash ps aux
    - run: docker logs clash
    - run: docker exec clash echo 'Direct ip' ;curl -s cip.cc | sed '4,100d' ; echo ''; echo 'Proxy ip' ; curl icanhazip.com





