name: AutoClash

on: [push]

jobs:
  job1:
    runs-on: ubuntu-latest
    env:
      TZ: Asia/Shanghai
      VERSION: "0.2"
      DOCKERHUB: "${{ secrets.DOCKERHUB_USERNAME }}/autoclash"
      
    timeout-minutes: 10
    steps:
    - uses: actions/checkout@v3
    - run: docker build -t ${DOCKERHUB}:${VERSION} docker/.
    -
      name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - 
      name: Push
      run: docker push ${DOCKERHUB}:${VERSION}
    - run: docker run -itd --privileged --name clash ${{ secrets.DOCKERHUB_USERNAME }}/autoclash:0.1 bash
    - run: docker ps
    - run: docker logs clash
    - run: docker exec clash ps aux
    - run: docker exec clash echo 'Direct ip' ;curl -s cip.cc | sed '4,100d' ; echo ''; echo 'Proxy ip' ; curl icanhazip.com
    - run: docker exec clash ./start.sh
    - run: docker exec clash ps aux
    - run: docker exec clash echo 'Direct ip' ;curl -s cip.cc | sed '4,100d' ; echo ''; echo 'Proxy ip' ; curl icanhazip.com





