name: AutoClash

on: [push]

jobs:
  job1:
    runs-on: ubuntu-latest
    env:
      TZ: Asia/Shanghai
      
    timeout-minutes: 10
    steps:
    - uses: actions/checkout@v3
    - run: docker build -t ubuntu/clash:0.1 docker/.
    - run: docker images
    - run: docker ps -a
    -
      name: Checkout
      uses: actions/checkout@v2
    -
      name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    -
      name: Login to DockerHub
      uses: docker/login-action@v1
      with:
          username: "${{ secrets.REGISTRY_USERNAME }}"
          password: "${{ secrets.REGISTRY_PASSWORD }}"
    - name: Build && Push
      uses: docker/build-push-action@v3
      with:
          context: .
          platforms: |
            linux/amd64
          file: docker/Dockerfile
          push: true
    





