name: AutoClash

on: [push]
env:
  VERSION: 0.2
  DOCKERHUB: "${{ secrets.DOCKERHUB_USERNAME }}/autoclash"
jobs:
  job1:
    runs-on: ubuntu-latest
    env:
      TZ: Asia/Shanghai
    timeout-minutes: 10
    steps:
    - uses: actions/checkout@v3
    - run: echo "${DOCKERHUB}:${VERSION}"
    - run: docker build -t "${DOCKERHUB}:${VERSION}" docker/.
    -
      name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - 
      name: Push
      run: docker push ${DOCKERHUB}:${VERSION}
    - run: docker run -itd --privileged --name=clash "${DOCKERHUB}:${VERSION}" bash
    - run: docker ps
    - run: docker ps -a
    - run: docker logs clash
    - run: docker exec clash ps aux
    - run: docker exec clash echo 'Direct ip' ;curl -s cip.cc | sed '4,100d' ; echo ''; echo 'Proxy ip' ; curl icanhazip.com
    - run: docker exec clash ./start.sh
    - run: docker exec clash ps aux
    - run: docker logs clash
    - run: docker exec clash echo 'Direct ip' ;curl -s cip.cc | sed '4,100d' ; echo ''; echo 'Proxy ip' ; curl icanhazip.com





