name: AutoClash

on:
  push: 
    branches:
      - main
      - '/.github/workflows/main.yml'

jobs:
  job1:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - run: apt update && apt install -y wget curl
    - run: python3 -V
    - run: pwd
    - run: docker build -t ubuntu/clash:0.1 docker/.
    - run: docker images
    - run: docker ps -a





