name: AutoClash
env:
  VERSION: 0.2
on: [push]
jobs:
  job1:
    runs-on: ubuntu-latest
    env:
      TZ: Asia/Shanghai
      DHV: ${{ secrets.DOCKERHUB_USERNAME }}/autoclash:${VERSION}
    timeout-minutes: 10
    steps:
    - uses: actions/checkout@v3
    - run: echo $DHV
    - run: docker build -t $DHV docker/.
    -
      name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - 
      name: Push
      run: docker push $DHV
    - run: docker run -itd --privileged --name=clash ${DHV} bash
    - run: docker ps
    - run: docker ps -a
    - run: docker logs clash
    - run: docker exec clash ps aux
    - run: docker exec clash echo 'Direct ip' ;curl -s cip.cc | sed '4,100d' ; echo ''; echo 'Proxy ip' ; curl icanhazip.com
    - run: docker exec clash ./start.sh
    - run: docker exec clash ps aux
    - run: docker logs clash
    - run: docker exec clash echo 'Direct ip' ;curl -s cip.cc | sed '4,100d' ; echo ''; echo 'Proxy ip' ; curl icanhazip.com





