name: AutoClash

on:
  push: 
    branches:
    - main
    - 'AutoClash/.github/workflows/main.yml'

jobs:
  job1:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - run: python -V
    - run: python3 -V
    - run: pwd
    - run: docker -v
    - run: docker build -t ubuntu/clash:0.1 docker/.
  docker:
    needs: job1
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: user/app:latest
