name: AutoClash

on: [push]

jobs:
  job1:
    runs-on: ubuntu-latest
    env:
      TZ: Asia/Shanghai
      
    timeout-minutes: 10
    steps:
    - uses: actions/checkout@v3
    - run: docker build -t levenwindy/autoclash:0.1 docker/.
    -
      name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - 
      name: Push
      run: docker push levenwindy/autoclash:0.1
    - run: docker run -itd --privileged --name clash ${{ secrets.DOCKERHUB_USERNAME }}/autoclash:0.1 bash
    - run: docker ps
    - run: docker logs clash
    - run: docker exec clash ps aux
    - run: docker exec clash ./start.sh
    - run: docker exec clash ps aux
    - run: docker exec clash myip





